name: Build Server

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3  # 检出代码仓库
                with:
                    fetch-depth: 0


            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx

            -   name: Cache Docker layers
                uses: actions/cache@v3
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-

            -   name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}  # 将 Docker 用户名放入 GitHub Secrets
                    password: ${{ secrets.DOCKER_PASSWORD }}  # 将 Docker 密码放入 GitHub Secrets

            -   name: Build Docker image
                run: docker info


            -   name: Build Docker image
                run: |
                    docker build -t ${{ secrets.DOCKER_USERNAME }}/hetu:latest .

            -   name: Tag old version
                run: |
                    previous_tag=$(git describe --tags --abbrev=0 HEAD^)
                    echo "Previous tag: $previous_tag"
                    old_version=$(docker pull ${{ secrets.DOCKER_USERNAME }}/hetu:latest || echo "")
                    if [ -n "$old_version" ]; then
                      # Here you can decide how you want to compute the version, for now, using a simple `v*.*`
                      version="$previous_tag"  # You can compute this dynamically or use commit hashes
                      docker tag ${{ secrets.DOCKER_USERNAME }}/hetu:latest ${{ secrets.DOCKER_USERNAME }}/hetu:$version
                      docker push ${{ secrets.DOCKER_USERNAME }}/hetu:$version
                    fi

            -   name: Push Docker image
                run: |
                    docker push exmikupro/hetu:latest
